import MarketNavbar from "@/_market/components/layout/MarketNavbar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Foodora | Market",
  description: "Generated by create next app",
};

export default function MarketLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="w-full overflow-x-hidden">
      <MarketNavbar />
      <main className="w-full relative mt-[120px] px-4 sm:px-8 md:px-10 lg:px-16 xl:px-20 2xl:px-36 pt-6">
        {children}
      </main>
    </div>
  );
}
